language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - FLASK_APP=quilt_server
    - FLASK_DEBUG=1
    - QUILT_SERVER_CONFIG=dev_config.py

services:
  - mysql

os:
  - linux

install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest
